version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mongodb
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=sunupointage

    depends_on:
      - mongodb
    networks:
      - app-network
    command: ["sh", "-c", "sleep 10 && php artisan migrate && apache2-foreground"]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    command: ["--wiredTigerCacheSizeGB", "1"]

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: