# Utilisation de l'image PHP-FPM officielle
FROM php:8.4-fpm

# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libicu-dev \
    libxml2-dev \
    zip \
    git \
    libpq-dev \
    libredis-dev && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd pdo pdo_mysql pdo_pgsql bcmath intl opcache && \
    pecl install redis && \
    docker-php-ext-enable redis

# Installer l'extension MongoDB pour PHP
RUN pecl install mongodb && docker-php-ext-enable mongodb

# Copier les fichiers du projet dans l'image Docker
COPY . /var/www/html

# Définir le répertoire de travail dans le conteneur
WORKDIR /var/www/html

# Installer Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Installer les dépendances PHP
RUN composer install --no-interaction --prefer-dist

# Copier le fichier .env si nécessaire
# Copier .env.example dans .env si le fichier .env n'existe pas déjà
RUN cp .env.example .env

# Exposer le port sur lequel le serveur PHP sera accessible
EXPOSE 8000

# Commande pour démarrer le serveur PHP-FPM
CMD ["php-fpm"]
