version: '3.8'

services:
  # Service pour l'application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=nom_base
      - DB_USERNAME=null
      - DB_PASSWORD=null

  # Service pour MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - laravel-net
    ports:
      - "27017:27017"

  # Service pour Nginx (facultatif, mais recommandé pour servir Laravel)
  nginx:
    image: nginx:latest
    container_name: nginx-laravel
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
