version: '3.8'

services:
  # Service pour l'application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017  # Utilisation du port interne 27017 de MongoDB
      - DB_DATABASE=sunupointage
      - DB_USERNAME=null
      - DB_PASSWORD=null
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "php-fpm"]  # Attente de MongoDB

  # Service pour MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - laravel-net
    ports:
      - "27018:27017"  # Le port 27018 de l'hôte est redirigé vers le port 27017 dans le conteneur

  # Service pour Nginx
  nginx:
    image: nginx:latest
    container_name: nginx-laravel
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
