version: '3.8'

services:
  # Service pour l'application Laravel
  backend:
      build:
        context: ./backend
      container_name: backend
      ports:
        - "8000:80"
      volumes:
        - ./backend:/var/www/html
      environment:
        - APP_ENV=local
        - DB_CONNECTION=mongodb
        - MONGO_DB_HOST=mongodb
        - MONGO_DB_PORT=27017
        - MONGO_DB_DATABASE=sunupointage

      depends_on:
        - mongodb
      networks:
        - app-network
      command: ["sh", "-c", "sleep 10 && php artisan migrate && apache2-foreground"]

  # Service pour MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - laravel-net
    ports:
      - "27018:27017"  # Le port 27018 de l'hôte est redirigé vers le port 27017 dans le conteneur


networks:
  laravel-net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
